dropChances:
  allay: 0.05
  axolotl: 0.05
  bat: 0.05
  bee: 0.05
  blaze: 0.05
  cat: 0.05
  cave_spider: 0.05
  chicken: 0.05
  cod: 0.05
  cow: 0.05
  creeper: 0.05
  charged_creeper: 0.025
  dolphin: 0.05
  donkey: 0.05
  drowned: 0.05
  elder_guardian: 0.05
  enderman: 0.05
  endermite: 0.05
  evoker: 0.05
  fox: 0.05
  frog: 0.05
  ghast: 0.05
  glow_squid: 0.05
  goat: 0.05
  guardian: 0.05
  hoglin: 0.05
  horse: 0.05
  husk: 0.05
  illusioner: 0.05
  iron_golem: 0.05
  llama: 0.05
  magma_cube: 0.05
  mushroom_cow: 0.05
  mule: 0.05
  ocelot: 0.05
  panda: 0.05
  parrot: 0.05
  phantom: 0.05
  pig: 0.05
  piglin: 0.05
  piglin_brute: 0.05
  pillager: 0.05
  polar_bear: 0.05
  pufferfish: 0.05
  rabbit: 0.05
  ravager: 0.05
  salmon: 0.05
  sheep: 0.05
  shulker: 0.05
  silverfish: 0.05
  skeleton_horse: 0.05
  slime: 0.05
  snowman: 0.05
  spider: 0.05
  squid: 0.05
  stray: 0.05
  strider: 0.05
  tadpole: 0.05
  trader_llama: 0.05
  tropical_fish: 0.05
  turtle: 0.05
  vex: 0.05
  villager: 0.05
  vindicator: 0.05
  wandering_trader: 0.05
  warden: 0.05
  witch: 0.05
  wither: 0.05
  wolf: 0.05
  zoglin: 0.05
  zombie_horse: 0.05
  zombie_villager: 0.05
  zombified_piglin: 0.05